disabled_rules:
  - trailing_whitespace
  - todo
  - line_length
  - type_body_length
  - file_length
  - function_body_length
opt_in_rules:
  - empty_count
  - closure_spacing
  - redundant_nil_coalescing
excluded:
  - Kneadly.xcodeproj
  - .build
identifier_name:
  min_length: 1
  excluded: [id, K, x, y, r, g, b, a, i, p, s, d, W, H, S]
